{{- $cloudProviderFlavor := include "shigola.cloudProviderFlavor" . -}}
{{- if and .Values.enabled .Values.route.enabled (eq $cloudProviderFlavor "openshift") -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "shigola.fullname" . }}
  labels:
    {{- include "shigola.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.route.rewriteTarget }}
    haproxy.router.openshift.io/rewrite-target: {{ .Values.route.rewriteTarget | quote }}
    {{- end }}
    {{- if .Values.route.timeout.enabled }}
    haproxy.router.openshift.io/timeout: {{ .Values.route.timeout.duration | quote }}
    {{- end }}
spec:
  {{- if .Values.route.host }}
  host: {{ .Values.route.host | quote }}
  {{- end }}
  path: {{ .Values.route.path | default "/" | quote }}
  to:
    kind: Service
    name: {{ include "shigola.fullname" . }}
  {{- if .Values.route.tls.enabled }}
  tls:
    termination: {{ .Values.route.tls.termination | quote }}
    insecureEdgeTerminationPolicy: {{ .Values.route.tls.insecureEdgeTerminationPolicy | quote }}
    {{- if .Values.route.tls.useCerts }}
    certificate: {{ .Values.route.tls.certificate | quote }}
    key: {{ .Values.route.tls.key | quote }}
    caCertificate: {{ .Values.route.tls.caCertificate | quote }}
    {{- end }}
  {{- end }}
{{- end }}
