{{- $databaseAuto := and .Values.database.enabled .Values.database.postgres.password (not .Values.database.postgres.passwordSecret.name) -}}
{{- $osmAuto := and .Values.osm.enabled .Values.osm.postgres.password (not .Values.osm.postgres.passwordSecret.name) -}}
{{- $redisAuto := and .Values.cache.redis.enabled .Values.cache.redis.password (not .Values.cache.redis.passwordSecret.name) -}}
{{- $s3Auto := and .Values.cache.s3.enabled (or .Values.cache.s3.accessKeyId .Values.cache.s3.secretAccessKey) (not .Values.cache.s3.credentialsSecret.name) -}}
{{- if and .Values.enabled (or $databaseAuto $osmAuto $redisAuto $s3Auto) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "shigola.fullname" . }}-generated
  labels:
    {{- include "shigola.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if $databaseAuto }}
  DATABASE_PGPASSWORD: {{ .Values.database.postgres.password | quote }}
  {{- end }}
  {{- if $osmAuto }}
  OSM_PGPASSWORD: {{ .Values.osm.postgres.password | quote }}
  {{- end }}
  {{- if $redisAuto }}
  REDIS_PASSWORD: {{ .Values.cache.redis.password | quote }}
  {{- end }}
  {{- if $s3Auto }}
  S3_ACCESS_KEY: {{ .Values.cache.s3.accessKeyId | quote }}
  S3_SECRET_KEY: {{ .Values.cache.s3.secretAccessKey | quote }}
  {{- end }}
{{- end }}
